//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.RavenDBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RavenDBService.IRavenDBProvider")]
    public interface IRavenDBProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRavenDBProvider/OpenSession", ReplyAction="http://tempuri.org/IRavenDBProvider/OpenSessionResponse")]
        void OpenSession(string database);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRavenDBProvider/OpenSession", ReplyAction="http://tempuri.org/IRavenDBProvider/OpenSessionResponse")]
        System.Threading.Tasks.Task OpenSessionAsync(string database);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRavenDBProviderChannel : Client.RavenDBService.IRavenDBProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RavenDBProviderClient : System.ServiceModel.ClientBase<Client.RavenDBService.IRavenDBProvider>, Client.RavenDBService.IRavenDBProvider {
        
        public RavenDBProviderClient() {
        }
        
        public RavenDBProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RavenDBProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RavenDBProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RavenDBProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void OpenSession(string database) {
            base.Channel.OpenSession(database);
        }
        
        public System.Threading.Tasks.Task OpenSessionAsync(string database) {
            return base.Channel.OpenSessionAsync(database);
        }
    }
}
